apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firezone-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: vps-platform
  source:
    # TODO: set to your infra repo URL (must match app-of-apps repoURL)
    repoURL: git@github.com:FR19/vps-infra.git
    targetRevision: main
    path: deploy/argocd/apps/firezone-gateway
    helm:
      releaseName: firezone-gateway
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: firezone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
