# Firezone Gateway - values
# Chart sourced from https://github.com/Intuinewin/helm-charts (firezone-gateway)

image:
  repository: ghcr.io/firezone/gateway
  pullPolicy: IfNotPresent
  tag: ""

logLevel: info
logFormat: json

config:
  apiUrl: wss://api.firezone.tukangketik.net
  token:
    key: FIREZONE_TOKEN
    existingSecret: firezone-gateway-token
  telemetry:
    enabled: true
  flowLogs:
    enabled: false

replicas: 1

securityContext:
  privileged: true
  readOnlyRootFilesystem: true

serviceAccount:
  create: true
  automount: false

revisionHistoryLimit: 10
autoscaling:
  enabled: false
pdb:
  enabled: false
