apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sogo-tls
  namespace: sogo
  labels:
    app.kubernetes.io/name: sogo
spec:
  secretName: sogo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - webmail.tukangketik.net
