apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sogo
resources:
  - namespace.yaml
  - configmap-sogo.conf.d.yaml
  - deployment-sonroyaalmerol.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
