apiVersion: v2
appVersion: 88521635c220edcb0134768760a169899c9c235e
description: A Helm chart for deploying firezone
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
name: firezone
type: application
version: 0.37.0
