apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headplane-tls
  namespace: headplane
spec:
  secretName: headplane-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - headplane.tukangketik.net
