apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:FR19/vps-infra.git
    targetRevision: main
    path: deploy/argocd/apps/mailu
    helm:
      valueFiles:
        - values.yaml
    kustomize:
      patches:
        - target:
            kind: Deployment
          patch: |
            spec:
              revisionHistoryLimit: 2
        - target:
            kind: StatefulSet
          patch: |
            spec:
              revisionHistoryLimit: 2
        - target:
            kind: DaemonSet
          patch: |
            spec:
              revisionHistoryLimit: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: mailu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
