apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vps-platform
  namespace: argocd
spec:
  description: VPS Microservices Platform
  sourceRepos:
    # TODO: set to your infra repo git URL
    - git@github.com:FR19/vps-infra.git
    - https://charts.gabe565.com
    - https://charts.jetstack.io
    - https://argoproj.github.io/argo-helm
    - https://charts.goauthentik.io
    - https://charts.bitnami.com/bitnami
    - https://github.com/jetstack/cert-manager
    - https://github.com/goauthentik/authentik
    - https://github.com/baarde/cert-manager-webhook-ovh
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
