apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jmap-webmail
  namespace: webmail
  labels:
    app.kubernetes.io/name: jmap-webmail
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webmail.tukangketik.net`)
      kind: Rule
      services:
        - name: jmap-webmail
          port: 3000
  tls:
    secretName: webmail-tls
