apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webmail
resources:
  - namespace.yaml
  # - secret-oauth.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
