apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-ovh-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fakhrur19.razi97@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-ovh-dns01-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.tukangketik.net
            solverName: ovh
            config:
              # OVH endpoints are region-specific. OVH Canada accounts must use ovh-ca.
              endpoint: ovh-ca
              authenticationMethod: application
              applicationKeyRef:
                name: ovh-credentials
                key: applicationKey
              applicationSecretRef:
                name: ovh-credentials
                key: applicationSecret
              applicationConsumerKeyRef:
                name: ovh-credentials
                key: applicationConsumerKey
