apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd.application.yaml
  - cert-manager/cert-manager.application.yaml
  - cert-manager-issuers/cert-manager-issuers.application.yaml
  - authentik/authentik.application.yaml
  - octelium-cluster/octelium-postgresql.application.yaml
  - octelium-cluster/octelium-redis.application.yaml
  - octelium-client/octelium-client.application.yaml
  - mailu/mailu.application.yaml
