apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/argocd.application.yaml
  - cert-manager/cert-manager.application.yaml
  - cert-manager-issuers/cert-manager-issuers.application.yaml
  - authentik/authentik.application.yaml
  - headscale/headscale.application.yaml
  - headplane/headplane.application.yaml
  - tailscale-dns/tailscale-dns.application.yaml
  - mailu/mailu.application.yaml
