apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.application.yaml
  - cert-manager.application.yaml
  - cert-manager-issuers.application.yaml
  - authentik.application.yaml
