apiVersion: v2
name: argocd-wrapper
description: Wrapper chart to install Argo CD from upstream with repo-managed values
type: application
version: 0.1.0
appVersion: "2.13"
dependencies:
  - name: argo-cd
    version: "7.7.7"
    repository: https://argoproj.github.io/argo-helm
